### ISSUE TITLE
Proxy to "upstream" Token Info for non-JWT tokens

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-tokeninfo#13]
We need to pass through non-JWT tokens to our existing "upstream" (let's not call it "legacy") Token Info endpoint.

**Comment by hjacobs** [comment]
Work started on this, we have an incomplete PR here: #9

**Comment by lmineiro** [comment]
Incoming changes for this

**Comment by lmineiro** [comment]
Env variable is `UPSTREAM_TOKENINFO_URL`

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
The current implementation is deployed in our Zalando environment --- and works :smile:
