### ISSUE TITLE
Add circuit breakers and timeouts

### ISSUE THREAD

**Issue by lmineiro** [zalando/planb-tokeninfo#14]
The network calls should have circuit breakers and configurable timeouts

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
I also see that the golang http.ReverseProxy is not very smart about upstream failures (connect, timeouts) --- it will just throw up with "Internal Server Error".

**Comment by lmineiro** [comment]
Good point. It seemed clean and smart to just reuse the features already available. I guess we'll have to customize this a little bit further.
