### ISSUE TITLE
Add caching possibility for the tokeninfo

### ISSUE THREAD

**Issue by lmineiro** [zalando/planb-tokeninfo#16]
The proxied tokeninfo response should be cacheable.
The cache TTL should be configurable.
A default value of 60 seconds seems reasonable
A value of 0 can disable the cache

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
Upstream token caching was implemented in #28.
Changes were successfully deployed to our internal test and production environments.

**Comment by hjacobs** [comment]
Only successful responses (status code 200) are cached, we might consider caching non-200 responses too (?)

**Comment by hjacobs** [comment]
The new cache configuration options are documented here: https://github.com/zalando/planb-tokeninfo#configuration
