### ISSUE TITLE
Refreshing keys does not respect DNS TTL

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-tokeninfo#17]
As we are using default go HTTP client it uses connection pooling and keeps a connection open to the old endpoint (disregarding DNS switch).

**Comment by hjacobs** [comment]
Actually it's not as bad as it sounds: it would not have any LIVE impact as keys are stored in Cassandra and both stack versions would return the same data.

**Comment by lmineiro** [comment]
We stopped using the http.DefaultClient (via `http.Get`)
We're now using the circuit breaker with a custom client that disables keep alive
