### ISSUE TITLE
Serialize JWT Claims as part of the TokenInfo response

### ISSUE THREAD

**Issue by lmineiro** [zalando/planb-tokeninfo#23]
Some Claims from the JWT are translated to specific TokenInfo attributes, the remaining Claims should be transferred "as is" to the TokenInfo response.

**Comment by hjacobs** [comment]
:+1:

**Comment by LappleApple** [comment]
@lmineiro @hjacobs  Hey, can we close this issue? It dates back to Feb 2016.

Or, we could add a "Help Wanted" label.

**Comment by LappleApple** [comment]
cc @vroldanbet, should we add a "Help Wanted" label?

**Comment by vroldanbet** [comment]
@lmineiro FYI issue https://github.com/zalando/planb-tokeninfo/issues/79 enables functionality in this ticket

**Comment by lmineiro** [comment]
Closing this one. Please follow-up on #79
