### ISSUE TITLE
Add "truthy" attributes to Token Info response for all existing scopes

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-tokeninfo#29]
Because of e.g. https://github.com/zalando-stups/friboo/blob/master/src/org/zalando/stups/friboo/system/http.clj#L181

**Comment by lmineiro** [comment]
I'll cleanup this afterwards

**Comment by hjacobs** [comment]
@lmineiro I guess you will not work on this?

**Comment by LappleApple** [comment]
@hjacobs @lmineiro @vroldanbet  Hey, can we close this issue? It dates back to March 2016.

Or, we could add a "Help Wanted" label.

**Comment by vroldanbet** [comment]
Isn't this already implemented?
