### ISSUE TITLE
Revocation: Improve logging

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-tokeninfo#34]
We should log something more helpful than "\<nil\>" if the token was revoked...
```
2016/03/14 15:05:13 Failed to validate token:  <nil>
2016/03/14 15:05:14 Failed to validate token:  <nil>
2016/03/14 15:05:15 Failed to validate token:  <nil>

**Comment by jeffsantarossa** [comment]
Logging now prints 'Invalid JWT token', 'Token is revoked', or the error message if there was an error parsing.
