### ISSUE TITLE
Revocation: claim revocation can have multiple claim names

### ISSUE THREAD

**Issue by jeffsantarossa** [zalando/planb-tokeninfo#35]
Add logic to handle revocations that might have multiple claim names.

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
Required by https://github.com/zalando/planb-revocation/issues/63

**Comment by jeffsantarossa** [comment]
tested against [zalando/planb-revocation](https://github.com/zalando/planb-revocation) Merged into revocation branch.
