### ISSUE TITLE
Revocations: Don't allow future revocations

### ISSUE THREAD

**Issue by jeffsantarossa** [zalando/planb-tokeninfo#43]
During testing, we revoked a claim years in the future and weren't able to POST a ForceRefresh to the Revocation Service since we revoked any token that would allow us to POST. This should not happen.

Up for discussion: 
Do we not allow any kind of future revocations?
Allow future revocations for a certain timeframe (e.g. Revocation TTL)?
Only allow future revocations for certain types (e.g. TOKEN)?
(Currently tokeninfo will not accept Global revocations in the future)

@vroldanbet @gargravarr @danieldelhoyo @hjacobs

**Comment by hjacobs** [comment]
Revoking future tokens makes IMHO no sense as there are other ways of denying access (preventing token creation) in that case, e.g. changing the user's password or client secret.

**Comment by hjacobs** [comment]
I think this was implemented with #44 (to be confirmed)
