### ISSUE TITLE
Revocation: Add integration tests

### ISSUE THREAD

**Issue by jeffsantarossa** [zalando/planb-tokeninfo#50]
Similar to https://github.com/zalando/planb-revocation/issues/103.

We want to make sure all revocations are being stored in the cache.

Test the assumed worst case scenario: 300 revocations / minute \* 30 days (~ 13 million).

**Comment by LappleApple** [comment]
Hey @lmineiro @jeffsantarossa @hjacobs @vroldanbet, can we close this issue? It dates back to April 2016. 

Or, we could add a "Help Wanted" label.

**Comment by jeffsantarossa** [comment]
I think it can be closed.
