### ISSUE TITLE
tokeninfo endpoint is not considering revocations

### ISSUE THREAD

**Issue by matosf** [zalando/planb-tokeninfo#51]
After creating a revocation on a customer token, tokeninfo call is still considering the token as valid.

If you need script to replicate please ping me.

**Comment by hjacobs** [comment]
Could you give us some more (anonymized) details? What revocation type? What kind of claims, etc?

**Comment by matosf** [comment]
@hjacobs

Env. Setup:
```
export TOKENINFO_HOST=localhost:8080
export PROVIDER_HOST=localhost:8080
export REVOCATION_HOST=localhost:8080
```

Define the Customer Token to invalidate:
```
export CUSTOMER_TOKEN=123
```

Confirm that the Customer Token is valid:
```
curl -v -X GET "https://${TOKENINFO_HOST}/oauth2/tokeninfo?access_token=${CUSTOMER_TOKEN}"
```

Get the Service Token:
```
curl -v -X POST -H "Authorization: Basic dGVzdDA6dGVzdDA=" -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: application/json" -d 'grant_type=password&username=test0&password=test0&realm=/services&scope=uid cn azp' "https://${PROVIDER_HOST}/oauth2/access_token"
```

Define the Service Token to use in the Customer Token invalidation:
```
export SERVICE_TOKEN=123
```

Invalidate the Customer Token:
```
curl -v -X POST -H "Authorization: Bearer ${SERVICE_TOKEN}" -H "Content-Type: application/json" --insecure -d '{"type": "TOKEN","data": {"token": "${CUSTOMER_TOKEN}"}}' "https://${REVOCATION_HOST}/revocations"
```

Confirm that the Customer Token is now invalid:
```
curl -v -X GET "https://${TOKENINFO_HOST}/oauth2/tokeninfo?access_token=${CUSTOMER_TOKEN}"
```

**Comment by hjacobs** [comment]
@gargravarr @jeffsantarossa can you check this?

**Comment by jeffsantarossa** [comment]
@matosf @hjacobs @gargravarr 
I'm on holiday until April 25th. I might not be able to do any testing this week, but will definitely look into it when I'm back.

**Comment by gargravarr** [comment]
@hjacobs on Friday 2016-04-15 @matosf reported me the issue and I did some tests with the Revocation service which confirmed that revocations are being properly inserted.

For reference, it is tested [here](https://github.com/zalando/planb-revocation/blob/master/src/test/java/org/zalando/planb/revocation/api/RevocationResourceIT.java#L146)

**Comment by jeffsantarossa** [comment]
@matosf 

When you're POSTing to the revocation service, you're using single quotes for the json:
'{"type": "TOKEN","data": {"token": "${CUSTOMER_TOKEN}"}}'
You're literally passing ${CUSTOMER_TOKEN} in as the token to revoke instead of the actually JWT token (bash doesn't evaluate the variable when using single quotes). 

Please try pasting the actual customer token into the POST and let me know if that solves the issue.

**Comment by matosf** [comment]
@jeffsantarossa 
I don't think that is the problem, because I just tested using the exact same script and now it works, the token is revoked and I get a 401 in the last call.
Was some change introduced in meantime?
