### ISSUE TITLE
Improve flaky circuit breaker tests

### ISSUE THREAD

**Issue by lmineiro** [zalando/planb-tokeninfo#54]
Some times the circuit breaker tests fail due to some timing issues. Should be improved

**Comment by LappleApple** [comment]
@lmineiro @vroldanbet Hey, can we close this issue? It dates back to April 2016. 

Or, we could add a "Help Wanted" label.

**Comment by vroldanbet** [comment]
I never saw them failing, tbh.

**Comment by LappleApple** [comment]
@vroldanbet Let's close, then, as this is very old. If the issue comes up again, someone will say so, I imagine. :)
