### ISSUE TITLE
Allow running without UPSTREAM_TOKENINFO_URL

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-tokeninfo#56]
We should support running Token Info without an upstream token info endpoint (Plan B might be deployed standalone). Currently it will not start without the env var: 

```
Error with UPSTREAM_TOKENINFO_URL: Missing URL setting: "UPSTREAM_TOKENINFO_URL"
```

**Comment by lmineiro** [comment]
Sounds legit. I'll do it

**Comment by LappleApple** [comment]
@lmineiro Hey, did you do it? 

This issue dates to May 2016; can we close it or add a 'help wanted" label? cc @vroldanbet

**Comment by vroldanbet** [comment]
@LappleApple we would most likely eventually need it. But not yet :)

**Comment by LappleApple** [comment]
@vroldanbet want to add a "Help Wanted" label?

**Comment by vroldanbet** [comment]
thanks @vetinari for handling this! Merged into master.
