### ISSUE TITLE
Implement revocation mechanism

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-tokeninfo#6]
We need to implement some revocation mechanism:

* download revocation lists periodically from [Revocation Service](https://github.com/zalando/planb-revocation) (poll for deltas)
* implement whatever revocation logic we decide to support (e.g. arbitrary claim based revocations)

**Comment by hjacobs** [comment]
@jeffsantarossa could you please merge the "master" branch into your "revocations" branch? I would like to review the current state :smile:

**Comment by jeffsantarossa** [comment]
@hjacobs Merged.

**Comment by hjacobs** [comment]
@jeffsantarossa I think you can create a pull request where we can continue the discussion and invite people to review :smile:

**Comment by jeffsantarossa** [comment]
Merged into master.
