### ISSUE TITLE
Remove "open_id" entry from response

### ISSUE THREAD

**Issue by vroldanbet** [zalando/planb-tokeninfo#65]
On a request of information over a token, planb-tokeninfo responds a field "open_id" token with the same contents as "access_token". This does not correspond to a real "id_token" so it should be removed.

**Comment by cgmv** [comment]
I somewhat disagree - the field `open_id` should be rename to `id_token` to be in coherence to the spec. Removing it is IMHO not the solution. 

Additionally we should instruct application owners to obfuscate or drop unused fields to prevent this from happening in the first place.

**Comment by vroldanbet** [comment]
@cgmv open_id is not part of the spec. We do not support "id_token" currently and our "access_token" is not strictly an OpenID Connect token beyond being a JWT token, there is missing information, so it cannot be used as is.
