### ISSUE TITLE
Validation fails if scope or realm claims are missing from the Token

### ISSUE THREAD

**Issue by vroldanbet** [zalando/planb-tokeninfo#71]
The absence of claims:
- realm
- scope

Makes the validation of the token fail.

Make these claims optional when validating the token.

**Comment by lmineiro** [comment]
If memory doesn't fail, realm, at least, was a mandatory claim in our design.

**Comment by vroldanbet** [comment]
would it make sense to make this optional? If feels like tokeninfo should focus on the signature of the token, fundamentally. In other use-case scenarios where realm and scope are not mandatory (or do not apply), validation fails, while the token is still properly signed. What do you think, @lmineiro ?

**Comment by lmineiro** [comment]
That would be mostly true if it wasn't for the revocation subscription which offers the possibility to revoke entire realms, for example.

I also believe the planb-provider always generates tokens with the mentioned claims. Is this a concern with inter-operability with other systems?

**Comment by vroldanbet** [comment]
@lmineiro revocation revokes by claim, so only applies if the claim is present.

Yes, planb-provider generates those claims in the token. I would like to see tokeninfo being able to generate tokens generated from other systems other than planb-provider, so it's indeed some sort of interoperability issue.

**Comment by hjacobs** [comment]
I think we can make those claims optional, at least it won't hurt us here --- revocation by realm is irrelevant if the claim is missing because we can assume that the current apps also won't authorize without it.

**Comment by lmineiro** [comment]
Sounds legit. The first place to change, it seems, would be in the `newTokenInfo()` function https://github.com/zalando/planb-tokeninfo/blob/master/handlers/tokeninfo/jwt/tokeninfo.go#L77

**Comment by vroldanbet** [comment]
@hjacobs @lmineiro thanks, had a patch ready, wanted to discuss it first :)

**Comment by vroldanbet** [comment]
Not necessary anymore from Zalando side
