### ISSUE TITLE
Add HTTP endpoint to list all known public keys

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-tokeninfo#8]
We should add an endpoint to list all known public keys in order to verify that the tokeninfo service is up-to-date.

**Comment by lmineiro** [comment]
:+1:

**Comment by lmineiro** [comment]
Do you think it is enough to list the key ids? We could piggyback such information as a short header/metadata in the metrics endpoint.

Since we should regularly poll those anyway, we could use it to gather such information also.

**Comment by hjacobs** [comment]
I believe an "exact" copy of the OIDC endpoint would be nicer (/oauth2/v3/certs), so we have a "distributed" store of the public keys and it's "standardized".
